Task 1

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:

def infinity():
    try:
        a = 5/0
        return a
    except Exception as e:
        print(repr(e))


infinity()

ZeroDivisionError('division by zero',)


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [2]:
subjects = ["Americans ", "Indians"]
verbs = ["play", "watch"]
objects = ["Baseball",  "Cricket"]

for i in range(2):
    for j in range(2):
        for k in range(2):
            print(subjects[i] + ' ' + verbs[j] + ' ' + objects[k], end='.\n')

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Task 2

1.

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [3]:
import numpy as np

def myVander(vector, num=None, increasing=False):
    a = []
    if num:
        N = num
    else:
        N = len(vector)

    for i in range(N):
        if increasing is True or increasing == 'T':
            a.append(vector ** i)
        else:
            a.append(vector ** (N - i - 1))

    matrix = np.array(a, ndmin=2)
    print(matrix.T)


numbers = input("Enter vector numbers: ")
if ',' in numbers:
    mylist = [int(num) for num in numbers.split(',') if num.strip().isdigit()]
else:
    mylist = [int(num) for num in numbers.split() if num.strip().isdigit()]

n = input("Enter number of columns to be displayed in output: ")
if n:
    n = int(n)
increasing = input("Type T for increasing order or skip: ")
vector = np.array(mylist)
myVander(vector, n, increasing)


Enter numbers of vector: 1 2 3 5
Enter number of columns to be displayed in output: 
Type T for increasing order or skip: T
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
